/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 100210
 Source Host           : localhost:3306
 Source Schema         : ytdata

 Target Server Type    : MySQL
 Target Server Version : 100210
 File Encoding         : 65001

 Date: 01/04/2021 07:35:19
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for comment
-- ----------------------------
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SourceMedia` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `AccountID` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Title` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `CommentID` int(11) NOT NULL,
  `Username` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `Text` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `TimePosted` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `CountOfReply` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `upvotes` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `CreatedTime` datetime(0) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 126 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of comment
-- ----------------------------
INSERT INTO `comment` VALUES (1, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 0, 'Lazuardi Akmal', 'Fatah ki Dustin e Comedy Sunday ', '3 hours ago', '', '19', '2021-03-31 22:58:54');
INSERT INTO `comment` VALUES (2, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 1, 'Ananda Conan', 'Aku lebih seneng notif teko comedy sunday timbang ane notif teko google classroom', '1 hour ago', '', '5', '2021-03-31 22:58:54');
INSERT INTO `comment` VALUES (3, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 2, 'Simoeh Paris', 'Setelah sekian purnomo tk enteni akhir e seng tak enteni njedul ', '1 hour ago', '', '2', '2021-03-31 22:58:54');
INSERT INTO `comment` VALUES (4, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 3, 'Candra', 'Jasa skip punchline 035', '3 hours ago', '', '22', '2021-03-31 22:58:54');
INSERT INTO `comment` VALUES (5, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 4, 'Iqbal Tsalitsin', 'wowkowk aku seneng iki rek fatah wes mulai wani jarak', '3 hours ago', '', '6', '2021-03-31 22:58:55');
INSERT INTO `comment` VALUES (6, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 5, 'Uhfi Nurike', 'Gak eroh anjerr saben nyawang Renaldi kuwudu guyu', '2 hours ago', '', '2', '2021-03-31 22:58:55');
INSERT INTO `comment` VALUES (7, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 6, 'Rafi Ramndani', 'Gasss', '4 hours ago', '', '1', '2021-03-31 22:58:55');
INSERT INTO `comment` VALUES (8, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 7, 'fairuz ramadhan', 'Aji randa lek ngomong babi iso muaaanteb ', '2 hours ago', '', '5', '2021-03-31 22:58:55');
INSERT INTO `comment` VALUES (9, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 8, 'MartuZ Tv 07', 'yang kutunggutunggu', '3 hours ago', '', '8', '2021-03-31 22:58:55');
INSERT INTO `comment` VALUES (10, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 9, 'adit vnm', 'ahhh rodo kerass\n\nsutoyo kabel', '2 hours ago', '', '2', '2021-03-31 22:58:56');
INSERT INTO `comment` VALUES (11, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 10, 'EGARA DINNUL IZA', 'jos akhirnya hadir wes tak enteni', '4 hours ago', '', '2', '2021-03-31 22:58:56');
INSERT INTO `comment` VALUES (12, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 11, 'Meck Toretto', 'Model e Fatah koyok jabro ', '3 hours ago', '', '6', '2021-03-31 22:58:56');
INSERT INTO `comment` VALUES (13, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 12, 'ahmad azka', 'Fatah Kon gundol ae boss', '3 hours ago', '', '4', '2021-03-31 22:58:56');
INSERT INTO `comment` VALUES (14, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 13, 'Tiar Tacong', 'Kanggo mas donoojo syuting aeaku ngenteni sampean muncul nk garingan', '3 hours ago', '', '3', '2021-03-31 22:58:57');
INSERT INTO `comment` VALUES (15, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 14, 'Rp17.000', 'Sumpah mas. Aku lebih seneng notif iki drpd notif e bojoku dikongkon ndang moleh ae', '1 minute ago', '', '', '2021-03-31 22:58:57');
INSERT INTO `comment` VALUES (16, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 15, 'Andre Januar', 'Josss cak ', '2 hours ago', '', '', '2021-03-31 22:58:57');
INSERT INTO `comment` VALUES (17, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 16, 'Beri Trisandi', 'bahas Banyuwangi mneh apik rek', '3 hours ago', '', '', '2021-03-31 22:58:57');
INSERT INTO `comment` VALUES (18, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 17, 'ASYROF MUZAKKI', 'Fatah guyon e sepele tapi gokil wkwkw', '1 hour ago', '', '', '2021-03-31 22:58:57');
INSERT INTO `comment` VALUES (19, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 18, 'fajar apridiant', 'Lucu gak lucu gakpopo sing penting wes subscribe ', '2 hours ago', '', '', '2021-03-31 22:58:58');
INSERT INTO `comment` VALUES (20, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 19, 'Fauzan Nr', 'min jal di wei subtitel bagian ngakak e ora nggenah malah', '2 hours ago', '', '', '2021-03-31 22:58:58');
INSERT INTO `comment` VALUES (21, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 20, 'Ibu 2 Bapak vs Ibu 2 Anak', 'Sudah kutunggu', '2 hours ago', '', '', '2021-03-31 22:58:58');
INSERT INTO `comment` VALUES (22, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 21, 'Ike Kumalasari', 'Pipiku sampe pegel oleh e guyu cak', '3 hours ago', '', '1', '2021-03-31 22:58:58');
INSERT INTO `comment` VALUES (23, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 22, 'Iza Najda', 'Mas Dono masih shooting film kah', '2 hours ago', '', '', '2021-03-31 22:58:59');
INSERT INTO `comment` VALUES (24, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 23, 'Reza Reza', 'Gur 20 menit an Kurang suwe ', '3 hours ago', '', '', '2021-03-31 22:58:59');
INSERT INTO `comment` VALUES (25, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 24, 'Mas Johnson', 'Guilani mas fir ', '27 minutes ago', '', '', '2021-03-31 22:58:59');
INSERT INTO `comment` VALUES (26, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 25, 'Dnd vrlya', 'Bapaknya jalannya Geter opo kesetrum a', '3 hours ago', '', '1', '2021-03-31 22:58:59');
INSERT INTO `comment` VALUES (27, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 26, 'm hawaril', 'fatah mesti lawucu wkwkwk', '58 minutes ago', '', '', '2021-03-31 22:58:59');
INSERT INTO `comment` VALUES (28, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 27, 'Ike Adelia', 'Firza yang tersakiti ', '2 hours ago', '', '', '2021-03-31 22:59:00');
INSERT INTO `comment` VALUES (29, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 28, 'Prayuda Phewe', 'Solehpati resikan saiki ..', '58 minutes ago', '', '', '2021-03-31 22:59:00');
INSERT INTO `comment` VALUES (30, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 29, 'Dimas Ananda Febriansyah', 'cok fatah nandi2 kenek terus wkkwkwkw', '1 hour ago', '', '', '2021-03-31 22:59:00');
INSERT INTO `comment` VALUES (31, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 30, 'Alisa Rahmat', 'Kalo gak ada Dono Pradana rasanya kek ada yg kurang..\nTpi tetap setia sama garingan..', '36 minutes ago', '', '', '2021-03-31 22:59:00');
INSERT INTO `comment` VALUES (32, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 31, 'XMM24Dimas Candra Winata', 'Tumben upload cepet', '4 hours ago', '', '', '2021-03-31 22:59:00');
INSERT INTO `comment` VALUES (33, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 32, 'mahdi zulkarnain', 'Perane patah dadi anak au...is tah ', '2 hours ago', '', '', '2021-03-31 22:59:01');
INSERT INTO `comment` VALUES (34, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 33, 'Harvian Khusnan H', 'AKHIRNYA', '44 minutes ago', '', '', '2021-03-31 22:59:01');
INSERT INTO `comment` VALUES (35, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 34, 'Sebuah Nama', 'Tah tah potongan mu kui lho....', '1 hour ago', '', '', '2021-03-31 22:59:01');
INSERT INTO `comment` VALUES (36, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 35, 'Benn', 'lhak ngenea ndagel ancok iku', '2 hours ago', '', '', '2021-03-31 22:59:02');
INSERT INTO `comment` VALUES (37, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 36, 'Fdhll By Hq', 'Subbhanaalahhh walhandulillah', '4 hours ago', '', '', '2021-03-31 22:59:02');
INSERT INTO `comment` VALUES (38, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 37, 'Naufal Yuwafi', 'Bangke ', '2 hours ago', '', '', '2021-03-31 22:59:02');
INSERT INTO `comment` VALUES (39, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 38, 'Ridho Khuzaini', '1046 medannya keluar', '23 minutes ago', '', '', '2021-03-31 22:59:03');
INSERT INTO `comment` VALUES (40, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 39, 'Nex Zero', 'Ya ampuunn', '4 hours ago', '', '1', '2021-03-31 22:59:03');
INSERT INTO `comment` VALUES (41, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 40, 'Aku jiblek', 'Mbok golek talent sing wedok to mas mas Ben kenek ngge obat moto sisan sing dadi ibuk e mosok Lanang terus', '3 hours ago', '', '1', '2021-03-31 22:59:03');
INSERT INTO `comment` VALUES (42, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 41, 'Rizky Yanuar', 'Hadirrr Ket moleh kerjo mas vir', '2 hours ago', '', '1', '2021-03-31 22:59:03');
INSERT INTO `comment` VALUES (43, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 42, 'Media Dokumentasi', 'Jawa jawa jawa', '1 hour ago', '', '1', '2021-03-31 22:59:03');
INSERT INTO `comment` VALUES (44, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 43, 'Dhani Tirta', 'Gerr', '2 minutes ago', '', '', '2021-03-31 22:59:04');
INSERT INTO `comment` VALUES (45, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 44, 'Saya Sendiri', 'Dono nang ndi kok gak tau metu', '3 hours ago', '', '1', '2021-03-31 22:59:04');
INSERT INTO `comment` VALUES (46, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 45, 'Andari Firgo', 'Gawe pempes lk ndelok iki..', '2 hours ago', '', '', '2021-03-31 22:59:04');
INSERT INTO `comment` VALUES (47, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 46, 'Dewangga Yoga', 'Cok rambut e fatah koyok kobochan ', '3 hours ago', '', '', '2021-03-31 22:59:04');
INSERT INTO `comment` VALUES (48, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 47, 'samuel sarwoko', 'Firza Jek eleng ae ambe marwal iskandar sangar cok', '15 minutes ago', '', '', '2021-03-31 22:59:04');
INSERT INTO `comment` VALUES (49, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 48, 'In Nk', 'Lucu gak lucu penting wes subscribe ', '1 hour ago', '', '', '2021-03-31 22:59:05');
INSERT INTO `comment` VALUES (50, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 49, 'W I C K S', 'Firza asu tenan hahaha', '3 hours ago', '', '', '2021-03-31 22:59:05');
INSERT INTO `comment` VALUES (51, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 50, 'Farid Anwar Hidayat', 'rambute fatah gamasuk', '4 minutes ago', '', '', '2021-03-31 22:59:05');
INSERT INTO `comment` VALUES (52, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 51, 'mahdi zulkarnain', 'Jenenge garingan tpi komedine ga garing blas komedine benyek', '2 hours ago', '', '', '2021-03-31 22:59:06');
INSERT INTO `comment` VALUES (53, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 52, 'Rian Wahyudi', 'mas dono nangdi', '3 hours ago', '', '', '2021-03-31 22:59:06');
INSERT INTO `comment` VALUES (54, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 53, 'Al Ayyuby', 'sonka.id ', '3 hours ago', '', '1', '2021-03-31 22:59:06');
INSERT INTO `comment` VALUES (55, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 54, 'Jimmy DT', '4 dino gak isok lego ndelok comedy sunday soale ujian', '39 minutes ago', '', '', '2021-03-31 22:59:06');
INSERT INTO `comment` VALUES (56, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 55, 'KoJOk', 'Kalo kata bocil\n\nFirst bang', '2 hours ago', '', '', '2021-03-31 22:59:06');
INSERT INTO `comment` VALUES (57, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 56, 'Qorypuspita Rani', 'ndelok potongan e fatah garai pengen mie ayam', '4 hours ago', '', '', '2021-03-31 22:59:07');
INSERT INTO `comment` VALUES (58, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 57, 'Allday.z', '1047 angel', '3 hours ago', '', '', '2021-03-31 22:59:07');
INSERT INTO `comment` VALUES (59, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 58, 'tya tazz', '', '1 hour ago', '', '', '2021-03-31 22:59:07');
INSERT INTO `comment` VALUES (60, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 59, 'Wayang 21', 'Cie komika ganteng suci 7', '3 hours ago', '', '', '2021-03-31 22:59:07');
INSERT INTO `comment` VALUES (61, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 60, 'Adam Akbar', 'Menit 1039 ada suara aneh wkwkwkwk', '1 hour ago', '', '', '2021-03-31 22:59:07');
INSERT INTO `comment` VALUES (62, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 61, 'Hisaludhin Radiansyah', 'budayakan20menit', '2 hours ago', '', '', '2021-03-31 22:59:08');
INSERT INTO `comment` VALUES (63, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 62, 'Fungky Yuni W', 'karo mas don maneh dong', '4 hours ago', '', '', '2021-03-31 22:59:08');
INSERT INTO `comment` VALUES (64, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 63, 'Piece Of sheet', 'Tak titeni nek eneng renaldi mesti garingan i mesti gak lucu', '3 hours ago', '', '', '2021-03-31 22:59:08');
INSERT INTO `comment` VALUES (65, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 64, 'BIMO GAMING', 'Joss comedy sunday', '2 hours ago', '', '', '2021-03-31 22:59:08');
INSERT INTO `comment` VALUES (66, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 65, 'Reda Saragi', 'Ripai', '1 hour ago', '', '', '2021-03-31 22:59:09');
INSERT INTO `comment` VALUES (67, 'YouTube', 'Comedy Sunday,', 'INI CARA MEMADU ISTRI  GARINGAN Eps. 14', 66, 'Bolang MTvlog', 'Menit 1137\nFatah menang akeh', '2 hours ago', '', '', '2021-03-31 22:59:09');
INSERT INTO `comment` VALUES (68, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 0, 'Buruh Laut', 'Sayang e bapak ibu ku wes gak enek kabeh ', '1 month ago', '', '2', '2021-03-31 23:02:28');
INSERT INTO `comment` VALUES (69, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 1, 'Fajar Sew', 'Beruntung bgt mbak dila punya keluarga yg selalu support', '1 month ago', '', '1', '2021-03-31 23:02:28');
INSERT INTO `comment` VALUES (70, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 2, 'NICEMERCY OH 2542', 'maas tooopikkk  cilegon hadir..hadirin penyiar2 radio di soloraya untuk di ajak pots', '2 weeks ago', '', '', '2021-03-31 23:02:28');
INSERT INTO `comment` VALUES (71, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 3, 'Alim K', 'Kapan Karo mas Indra meneh jonn', '1 month ago', '', '', '2021-03-31 23:02:28');
INSERT INTO `comment` VALUES (72, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 4, 'Yoga Sadewa', 'kui jok wedang klamutane mas topik', '1 month ago', '', '1', '2021-03-31 23:02:28');
INSERT INTO `comment` VALUES (73, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 5, 'Nabil Azmi', 'Sayange bapak ibuk ku ra kyk ngunu malah raruh kemampuanku kyk pye eruh e aku pinter padahal ora', '1 month ago', '', '1', '2021-03-31 23:02:29');
INSERT INTO `comment` VALUES (74, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 6, 'waton genjreng', 'menang', '1 month ago', '', '2', '2021-03-31 23:02:29');
INSERT INTO `comment` VALUES (75, 'YouTube', 'Topik Sudirman,', 'Diantara Dua Pilihan Faradila  POTS.28', 7, 'arrafi maulanq', 'Suarane mbake penyiar bet', '1 month ago', '', '1', '2021-03-31 23:02:29');
INSERT INTO `comment` VALUES (76, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 0, '', 'Ya Tuhan. Ini lagu enak sekali', '2 years ago', '', '1.7K', '2021-03-31 23:07:08');
INSERT INTO `comment` VALUES (77, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 1, 'Diky Sadega', 'Maaf aku mencintaimu dalam diam karena dalam diam aku tak menemui sebuah penolakan', '1 year ago', '', '184', '2021-03-31 23:07:10');
INSERT INTO `comment` VALUES (78, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 2, 'andika aldi', 'Lirik\n\nMemandang Indah Wajahmu\nMengagumi setiap lentik matamu', '2 years ago', '', '298', '2021-03-31 23:07:12');
INSERT INTO `comment` VALUES (79, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 3, 'Ery Wahidatul Khasanah', 'Untukmu yang sedang aku kagumi dalam diam. Memang semua ini salahku karena membawa perasaan dalam sebuah pertemanan ', '1 year ago', '', '97', '2021-03-31 23:07:15');
INSERT INTO `comment` VALUES (80, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 4, 'Edwin Mohamad Aldrin', 'Nak jikalau kamu membaca ini percayalah.. . bapak sedang memperjuangkan seseorang yg kelak menjadi ibumu ', '2 years ago', '', '300', '2021-03-31 23:07:17');
INSERT INTO `comment` VALUES (81, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 5, '', 'auto subscribe..salut atas karya nya..sendu tenan .. terossske mas lur ', '2 years ago', '', '341', '2021-03-31 23:07:19');
INSERT INTO `comment` VALUES (82, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 6, 'Kartika Putri', 'Aku baru sadarsebahagia ini kah aku ketika mengingat wajahmumeski dari jauh dahulu \n\nTangerang 12 Agustus 2020', '7 months ago', '', '11', '2021-03-31 23:07:21');
INSERT INTO `comment` VALUES (83, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 7, 'Don Sky', 'Kisah ku mas pik pacar ku iseh sok kelingan mantane iseh pengen hubungan karo mantane meneh opo o aku ki gur cah cilik cendik ireng elik sek tak umbul ke duwur gur roso ku nggo dek e iso luwih apik tumindake karo coro pikir ku suwun mas seenggake lagu iki penghibur sek marai grantes. Ku tak berhkak tuk paksakan hati mu. ', '2 years ago', '', '45', '2021-03-31 23:07:24');
INSERT INTO `comment` VALUES (84, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 8, 'Yoga Maulana Yusuf', '3 tahun nyenengi dewean\nNgeteni dekne bubaran ro yange ahire bubar\nPerlahan soyo cedek soyo nyaman\nTernyata aku seng ngroso nyaman dewe', '9 months ago', '', '16', '2021-03-31 23:07:26');
INSERT INTO `comment` VALUES (85, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 9, 'Never Surrender', 'Ya tuhan  jagalah jodohku dimanapun dia berada sekarang  pertemukanlah kami di saat yg tepat nanti', '2 years ago', '', '57', '2021-03-31 23:07:29');
INSERT INTO `comment` VALUES (86, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 10, 'Habib Fs', 'Greget mass. Ora kecewa lek ku ngenteni sue sue. Ayo trendingkan cah ', '2 years ago', '', '25', '2021-03-31 23:07:31');
INSERT INTO `comment` VALUES (87, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 11, 'Sri Amanda', 'Mencintai seseorang dalam diam karena dia telah memiliki kekasih ', '1 year ago', '', '10', '2021-03-31 23:07:33');
INSERT INTO `comment` VALUES (88, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 12, 'Al Rafi Enggar', 'Cuacane cerah yo\nya iya lah mergo udane tak pindah nang ati  \n', '1 year ago', '', '18', '2021-03-31 23:07:35');
INSERT INTO `comment` VALUES (89, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 13, 'Charysa Afzelsi Avrielya', 'Cinta dalam diam sakitnya bukan mainn', '2 years ago', '', '10', '2021-03-31 23:07:38');
INSERT INTO `comment` VALUES (90, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 14, '067 Ilham', 'Intine ngene. Mas topik nyenengi Clara. Mergo Clara ndue yang dadi nyenengine dalam diam. Padahal Clara ra bahagia karo yange. Gek Clara ngirone mas topik wes ndue yang. Clarane nyenengi mas topik dalam diam. Nah kabeh meneng menengan. Ngasi iPhone dadi android.', '2 years ago', '', '73', '2021-03-31 23:07:40');
INSERT INTO `comment` VALUES (91, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 15, 'ZAHWA BUNGA RANESTA UBP', 'Andai kamu tau aku diam diam memasang wallpaper foto kamu  aku tak pernah mengidolakan laki laki sampai seperti ini  semoga kita berjodoh ya  aamiin ', '3 months ago', '', '1', '2021-03-31 23:07:44');
INSERT INTO `comment` VALUES (92, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 16, 'Sri Handayani', 'Gue yg udah kagum sama seseorang sejak 5tahun lalu udah hampir 4tahun ngga ketemu dan kemaren sama hari ini ketemu ketawa becanda. Rasanya seneng banget tapi sayangnya dia udah punya pacar karna dia ngga tau perasaanku. Maap ya curhat dikit biar lega', '5 months ago', '', '2', '2021-03-31 23:07:49');
INSERT INTO `comment` VALUES (93, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 17, 'Livia Tri Banowati', 'Aku iseh sayang mantantgl 21 wingi putus mergo Dee seneng wong liosaiki dekne pacaran tapi dekne crito neng aku lak yange ra pengerten blablablaiso ku gor tetep nyenengi dekne meneng ambakno kecewa diselingkuhkemeh lungo seutuhe yo wes nyubo ga kuat mergo wes pacaran 1 tahun 2 bulansisuke tgl 8 asline 1 tahun 3 bulan tapi mah wes karo liane.Pie menurut e kalian', '4 months ago (edited)', '', '2', '2021-03-31 23:07:51');
INSERT INTO `comment` VALUES (94, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 18, 'Wong Ndeso', 'Nak kalo baca komentar ini aku ayahmu yg sedang memperjuangkan ibumu dlam diam.\n\nCilacap 22 januari 2020', '1 year ago', '', '7', '2021-03-31 23:07:54');
INSERT INTO `comment` VALUES (95, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 19, 'Amar Hafazz', 'Nggo koe aku tresno ro koe wes tak pendem 7 tahun wes tau ngomong tresno pas biyen neng nihil seneng rasane pen ketemu sedelo wong 2 lungguh crito tentang biyen neng saiki wes angel muk iso ndelok koe seko story WA ro IG ngono wae wes seneng mugo kwe bahagia ro dee ra ro aku', '8 months ago', '', '1', '2021-03-31 23:07:57');
INSERT INTO `comment` VALUES (96, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 20, 'Yoga Krismoni', 'mencintaimu dalam diam dan mendoakanmu setiap malam. caraku memelukmu dari kejauhan karena sudah ada orang lain yg kau panggil sayang', '1 year ago', '', '3', '2021-03-31 23:08:01');
INSERT INTO `comment` VALUES (97, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 21, 'Shidiq Setyo Adhi Nugroho', 'Untuk kalian yang sedang berjuang mencintai dalam diam jangan pernah putus asatuhan maha mendengar meski perasaan engkau pendam', '1 year ago', '', '3', '2021-03-31 23:08:05');
INSERT INTO `comment` VALUES (98, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 22, 'Ec Dork', 'Masukne ati lagumu mas kelingan dee aku. Soale aku demen ambek dee sui . Yo lek dee enek masalah opo aku mesti enek lalu mesti tak hibur terus tapi aku yo gur meneng tok arep omong ket disek Jan uangel eram mugo mugo dee moco komen ku iki lah soale dee sering rungok.ne.lagu ne sampean . Sek sek kok aku curhat yo', '2 years ago (edited)', '', '51', '2021-03-31 23:08:07');
INSERT INTO `comment` VALUES (99, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 23, 'Hanif Fauzan Ammar', '3 tahun hanya bisa mencintaimu dalam diam yang terpenting kamu bahagia walau kamu bersama orang lain \n\nSragen 27 Maret 2020.', '1 year ago', '', '4', '2021-03-31 23:08:10');
INSERT INTO `comment` VALUES (100, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 24, 'Siti Khadijah', 'Mungkin kurasa saat ini cukup untuk sekedar mengagumi dalam diam tanpa mengungkapkankarena kurasa untuk memiliki terlalu dini saat iniaku akan menunggu sampai Allah sendiri yang mempertemukan jika memang kita telah ditakdirkannamun jika tidak aku tidak akan menyesal pernah mengagumi sosok istimewa sepertimu dalam diam kuaku tidak akan pernah menyesal selalu menyebut namamu di 13 malamkukarena kamu juga aku merasakan bahagia walau akhirnya kini aku harus pergi dan beda kota.', '8 months ago', '', '4', '2021-03-31 23:08:13');
INSERT INTO `comment` VALUES (101, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 25, 'Pejuang Senyum', 'Cinta Dalam Diam Adalah Cinta Yang Murni karena Benar Benar Mencintai Bukan Hanya Karena Nafsu', '1 year ago', '', '1', '2021-03-31 23:08:16');
INSERT INTO `comment` VALUES (102, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 26, 'Cilyne Airi', 'sy hanya mampu menyimpan perasaan secara diam.. maafkan sy kerna membawa perasaan dlm persahabatan kita ni.. sy tak minta balasan cuma izinkan sya terus mengagumi km dalam diam.. jangan pernah menjauh dri sy..', '6 months ago', '', '1', '2021-03-31 23:08:18');
INSERT INTO `comment` VALUES (103, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 27, 'KhairinnisahD 24', 'Sekarang.aku lagi Mencintai orang dalam diam dengan menyebut namanya dihadapan allah\nMedan28 september 2020\nAku gak menyesal pernah mencintaimu', '6 months ago', '', '2', '2021-03-31 23:08:20');
INSERT INTO `comment` VALUES (104, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 28, 'Khanan Dwi Cahyo', 'Apa bener topik Sudirman waktu masih muda namanya topik sudirboy', '2 years ago', '', '137', '2021-03-31 23:08:22');
INSERT INTO `comment` VALUES (105, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 29, 'M. Hilman Iman Sakti', 'Gatau lagi apakah ada kata yg lebih bisa menggambarkan lagu ini luar biasa jeru mengagumkan katakata itu masih belum bisa menggambarkan betapa indah dan kuatnya lagu ini.', '9 months ago', '', '', '2021-03-31 23:08:25');
INSERT INTO `comment` VALUES (106, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 30, 'Caca Caca', '2 taun menyayangi dalam diam berjuang menguatkan hati bahwa jika memang yg ditakdirkan utkku tak akan pernah melewatkan ku', '7 months ago', '', '', '2021-03-31 23:08:27');
INSERT INTO `comment` VALUES (107, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 31, '', 'Yang ku takutkan mereka para pencinta dalam diam semakin menikmati keadaan nya Lewat aksara yg kau suarakan. ', '2 years ago', '', '1', '2021-03-31 23:08:29');
INSERT INTO `comment` VALUES (108, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 32, 'Khusnia Umi Amiroh', 'Mencintai dalam diam karena aku sadar level yang berbeda terlalu sempurna dan yah begitulah insecure dengan segala yang ada padanya tapi aku merasakan perasaan menyebalkan itu capek sebenernya begitu terus', '4 months ago', '', '', '2021-03-31 23:08:32');
INSERT INTO `comment` VALUES (109, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 33, 'Bonong Baik', 'Ya allah lagumu massss yuhh nancep ng ati ', '2 years ago', '', '37', '2021-03-31 23:08:34');
INSERT INTO `comment` VALUES (110, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 34, 'Bright Morning', 'Puter terus tapi kok ra bosen ya', '2 years ago', '', '', '2021-03-31 23:08:37');
INSERT INTO `comment` VALUES (111, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 35, 'Bhaskara Jagadhita', 'Upload SPOTIFY mass', '2 years ago', '', '6', '2021-03-31 23:08:39');
INSERT INTO `comment` VALUES (112, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 36, 'Mas Sdq', 'Pas bngt lagu nya sama keadaan sekarang. Walaupun udah 3thn lebih berhubungan sama dia. Tpi sekarang dia malah nyatain dgn gampang nya sdh gk punya perasaan. Dan sekarang gk pernah ketemu cuma via whatsapp.\n Ku hanya bisa diam menyimpan perasaan di dalam sebuah ruang yg ku sebut Rindu ', '1 year ago', '', '3', '2021-03-31 23:08:41');
INSERT INTO `comment` VALUES (113, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 37, 'Mikha Oktavia', 'gabisa diungkapin dengan kata2 cuman bisa nangisdan merindukan dia ', '1 year ago', '', '', '2021-03-31 23:08:44');
INSERT INTO `comment` VALUES (114, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 38, 'Gilang Pamungkas', 'Ferlina tika aulia saat nanti kamu dengerin lagi ini aku masih selalu mengingatmu dan jatuh dalam perasaan yang sama', '3 months ago', '', '', '2021-03-31 23:08:46');
INSERT INTO `comment` VALUES (115, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 39, 'Arya Ibnu pradana', 'Mugo wae kw ndelok lan ngrungokne lagu iki yo jul nek saktenane sakwise kejadian kae aku urung iso buka ruang ning atiku karo sakliane koe.', '1 year ago', '', '6', '2021-03-31 23:08:48');
INSERT INTO `comment` VALUES (116, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 40, 'Irvanbae 69', 'Ku Tak Berhak Tuk Paksakan Hatimu ', '2 years ago', '', '14', '2021-03-31 23:08:51');
INSERT INTO `comment` VALUES (117, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 41, 'teguh subandriyo', 'Rapopo mas kita adalah manifestasi jiwa2 kesepian \nSampean pancen ngaten ', '2 years ago', '', '6', '2021-03-31 23:08:56');
INSERT INTO `comment` VALUES (118, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 42, 'mas Takaa', 'Mas  kok koe ganteng pas lagi galau  opo rahasiamu  Jomblo  wkwk', '2 years ago', '', '46', '2021-03-31 23:09:03');
INSERT INTO `comment` VALUES (119, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 43, 'Hana Anggraini', 'Gatau kenapa aku terlalu pengecut untuk soal perasaan. Ngeliat orangnya aja ga berani. Apalagi menatap v Apalah dayaku yang hanya berani ngelihatnya dari kejauhan ', '5 months ago', '', '', '2021-03-31 23:09:06');
INSERT INTO `comment` VALUES (120, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 44, 'mahox poetra', 'Dan saiki cahe est kawin karo wong liyo \n\n\nPati 30 September 2019', '1 year ago', '', '11', '2021-03-31 23:09:10');
INSERT INTO `comment` VALUES (121, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 45, 'Dian Sepiati', 'Knpa Bru tau ada lagu bagus bgini skrng ', '7 months ago', '', '', '2021-03-31 23:09:15');
INSERT INTO `comment` VALUES (122, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 46, 'wildan fathoni', 'MUANTAP POL.. IKI KUDU TRENDING', '2 years ago', '', '', '2021-03-31 23:09:20');
INSERT INTO `comment` VALUES (123, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 47, 'taufik rhm', 'untukmu yang dulu ku perjuangkan matimatiansekarang aku sadar cinta tidak bisa di paksakan.mulai sekarang aku belajar merelakanmu entah  dengan siapa kau nanti semoga bahagia ', '1 year ago', '', '', '2021-03-31 23:09:24');
INSERT INTO `comment` VALUES (124, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 48, 'Yoga Agus', 'Waaaa yaaa ini karya mu yang ditunggu tunggu mas \n  \nLiriknya sangat memotivasi v ', '2 years ago', '', '28', '2021-03-31 23:09:26');
INSERT INTO `comment` VALUES (125, 'YouTube', 'Topik Sudirman,', 'Topik Sudirman  Mencintaimu Dalam Diam Official Video Clip', 49, 'alghifari putra', 'baper ndeee', '2 years ago', '', '1', '2021-03-31 23:09:29');

SET FOREIGN_KEY_CHECKS = 1;
